[package]
name = "farem-main"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
edgedb-tokio = "0.3.0"
rocket = "0.4.11"
tokio = { version = "1.21.1", features = ["rt", "macros"] }
