[package]
name = "compilers"
version = "0.1.0"
edition = "2021"
description = "This crate is responsible for compiling the different sources to webassembly"


[dependencies]
actix-web = "4.2.1"
duct = "0.13.5"
env_logger = "0.9.1"
log = "0.4.17"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
utilities = { path = "../../libs/utilities" }

[[bin]]
name = "cpp-compiler"
path = "src/bin/cpp.rs"

[[bin]]
name = "go-compiler"
path = "src/bin/go.rs"

[[bin]]
name = "rs-compiler"
path = "src/bin/rs.rs"
