yarnPath: .yarn/releases/yarn-3.2.3.cjs

nodeLinker: node-modules

# https://github.com/yarnpkg/berry/issues/4165
logFilters:
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
  - code: YN0013
    level: discard

enableGlobalCache: true

enableTelemetry: false
