[workspace]
members = [
  "libs/auth",
  "libs/config",
  "libs/domains",
  "libs/macros",
  "libs/utilities",
  "apps/farem-cpp",
  "apps/farem-go",
  "apps/farem-main",
  "apps/farem-rs",
  "apps/farem-run",
]
