[workspace]
members = [
  # libraries
  "libs/auth",
  "libs/config",
  "libs/domains",
  "libs/macros",
  "libs/utilities",

  # binaries
  "apps/compilers",
  "apps/farem-run",
  "apps/orchestrator",
]
