name: Setup

description: Setup global moon cli

inputs:
  moon-version:
    description: Moon version
    required: false
    default: '0.19.1'

runs:
  using: composite
  steps:
    - uses: supplypike/setup-bin@v1
      with:
        uri: 'https://github.com/moonrepo/moon/releases/latest/download/moon-x86_64-unknown-linux-musl'
        name: 'moon'
        version: ${{ inputs.moon-version }}
