name: Setup

description: Setup global moon cli

runs:
  using: composite
  steps:
    - shell: bash
      run: curl -fsSL https://moonrepo.dev/install.sh | bash

    - shell: bash
      run: echo '$HOME/.moon/tools/moon/latest' >> $GITHUB_PATH

    - shell: bash
      run: moon --version
