[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-graphql = { version = "4.0.14", features = ["log"] }
async-graphql-rocket = "4.0.13"
config = { path = "../../libs/config" }
domains = { path = "../../libs/domains" }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
edgedb-tokio = { git = "https://github.com/edgedb/edgedb-rust.git", branch = "master" }
figment = { version = "0.10.7", features = ["env"] }
protobuf = { path = "../../libs/protobuf" }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"
surf = { version = "2.3.2", features = ["hyper-client"] }
tokio = { version = "1.21.1", features = ["rt", "macros"] }
tonic = "0.8.2"
uuid = "1.1.2"
