version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - HANKO_URL=http://localhost:9000
      - HANKO_URL_INTERNAL=http://hanko-backend:9000
    user: archlinux

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  # from https://github.com/teamhanko/hanko/blob/main/deploy/docker-compose/quickstart.yaml

  hanko-database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - hanko_db_data:/var/lib/postgresql/data

  hanko-backend:
    image: ghcr.io/teamhanko/hanko:main
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    volumes:
      - ./config/hanko.yml:/config/config.yaml
    command: serve all
    ports:
      - 9000:9000 # public
      - 9001:9001 # admin

  hanko-migrate:
    image: ghcr.io/teamhanko/hanko:main
    volumes:
      - ./config/hanko.yml:/config/config.yaml
    command: migrate up

volumes:
  hanko_db_data:
