# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

fileGroups:
  # Application specific files
  app: []
  configs:
    - '*.{js,json,yml,yaml}'
  sources:
    - 'public/**/*'
    - 'src/**/*'
    - 'types/**/*'
  tests:
    - 'tests/**/*.test.*'
    - 'tests/**/*.stories.*'
    - '**/__tests__/**/*'

tasks:
  lint:
    command: 'rome check $projectRoot'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - 'rome.json'
    options:
      runFromWorkspaceRoot: true

  format:
    command: 'rome format'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - 'rome.json'
    options:
      runFromWorkspaceRoot: true

  test:
    command:
      - jest
      - '--coverage'
      - '--passWithNoTests'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - 'jest.config.*'

  typecheck:
    command:
      - tsc
      - '--build'
      - '--verbose'
    inputs:
      - '@group(app)'
      - '@globs(sources)'
      - '@globs(tests)'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - '/tsconfig.options.json'
