# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

fileGroups:
  # Application specific files
  app: []
  configs:
    - '*.{js,json,yml,yaml}'
  sources:
    - 'public/**/*'
    - 'src/**/*'
    - 'types/**/*'
  tests:
    - 'tests/**/*.test.*'
    - 'tests/**/*.stories.*'
    - '**/__tests__/**/*'

tasks:
  lint:
    command:
      - eslint
      - '--ext'
      - '.js,.jsx,.ts,.tsx'
      - '--fix'
      - '--report-unused-disable-directives'
      - '--no-error-on-unmatched-pattern'
      - '--exit-on-fatal-error'
      - '--ignore-path'
      - '@in(4)'
      - '.'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - '*.config.*'
      - '**/.eslintrc.*'
      - '/.eslintignore'
      - '/.eslintrc.*'
      - 'types/**/*'
      - 'tsconfig.json'
      - '/tsconfig.eslint.json'
      - '/tsconfig.options.json'

  test:
    command:
      - jest
      - '--coverage'
      - '--passWithNoTests'
    inputs:
      - 'src/**/*'
      - 'tests/**/*'
      - 'jest.config.*'

  typecheck:
    command:
      - tsc
      - '--build'
      - '--verbose'
    inputs:
      - '@group(app)'
      - '@globs(sources)'
      - '@globs(tests)'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - '/tsconfig.options.json'
