database:
  dialect: postgres
  user: '${DATABASE_USER}'
  password: '${DATABASE_PASSWORD}'
  host: '${DATABASE_HOST}'
  port: ${DATABASE_PORT}
  database: '${DATABASE_NAME}'

passcode:
  email:
    from_address: '${FROM_EMAIL}'
    from_name: '${FROM_NAME}'
  smtp:
    host: '${SMTP_HOST}'
    port: ${SMTP_PORT}
    user: '${SMTP_USER}'
    password: '${SMTP_PASSWORD}'

secrets:
  keys:
    - '${SECRET_KEY}'

service:
  name: 'Codefarem'

server:
  public:
    address: ':${PORT:-5000}'
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - '${SERVER_PUBLIC_CORS_ALLOW_ORIGIN}'

session:
  lifespan: '${SESSION_LIFESPAN:-24h}'
  cookie:
    domain: '${SESSION_COOKIE_DOMAIN}'
    http_only: true
    secure: true

audit_log:
  storage:
    enabled: true
