database:
  dialect: postgres
  host: $DATABASE_HOST
  port: $DATABASE_PORT
  user: $DATABASE_USER
  password: $DATABASE_PASSWORD
  database: $DATABASE_NAME

passcode:
  email:
    from_address: no-reply@codefarem.io
  smtp:
    host: mail
    port: 1025

secrets:
  keys:
    - secret-password-12345

service:
  name: Authentication Service

server:
  admin:
    address: ':9001'
  public:
    address: ':9000'
    cors:
      enabled: true
      allow_credentials: true
      allow_origins:
        - '*'

session:
  cookie:
    secure: false

audit_log:
  storage:
    enabled: true
