use async_graphql::{SimpleObject, Union};
use utilities::graphql::{ApiError, UserDetailsOutput};

#[derive(Debug, SimpleObject)]
pub struct UserDetailsGeneratedData {
    /// An svg avatar generated using the user's username
    pub profile_avatar: String,
}

#[derive(Debug, SimpleObject)]
pub struct UserDetailsDto {
    /// The data that was stored in the database
    pub db_data: UserDetailsOutput,
    /// The data that was generated by the server
    pub generated_data: UserDetailsGeneratedData,
}

/// The output object when creating a new user
#[derive(Union, Debug)]
pub enum UserDetailsResultUnion {
    /// The type returned if getting details about user was successful
    Result(UserDetailsDto),

    /// The type returned if getting details about user was unsuccessful
    Error(ApiError),
}
