name: 'Build and push containers to the Github registry'

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: 'Build the initial binaries and generate dockerfile(s)'
    runs-on: 'ubuntu-latest'
    outputs:
      executables: ${{ steps.executables.outputs.executables }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
        name: Setup Nodejs

      - uses: ./.github/actions/setup-moon
        name: Setup moon

      - uses: ./.github/actions/setup-rust
        name: Setup Rust

      - uses: ./.github/actions/setup-python
        name: Setup python environment

      - name: Setup moon dependencies
        run: moon setup

      - name: Get projects executables
        id: executables
        run: |
          all_executables=$(cat apps/deployment/src/data/*.json | jq -r '.apps[].EXECUTABLE_NAMES | flatten[]' | tr '\n' ' ' | xargs)
          executables=$(node -e "
            let executables = \`$all_executables\`.split(' ').filter(Boolean)
            console.log(JSON.stringify(executables))
          ")
          echo "executables=$executables" >> $GITHUB_OUTPUT
          echo "Discovered executables: $executables"

      - name: Generate project dockerfile(s)
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          for project in "authenticator" "languages" "executor" "orchestrator" "website" "admin-backend" "admin-website"
          do
            echo "Generating dockerfile for '$project'..."
            poetry run python apps/deployment/src/docker.py "$project"
          done

      - name: Build the Rust projects
        run: |
          for executable in "languages" "executor" "orchestrator" "admin-backend"
          do
            echo "Building executable '$executable'..."
            cargo build --release --package "$executable"
          done

      - name: Build the Nodejs projects
        run: |
          for executable in "website" "admin-website"
          do
            echo "Building executable '$executable'..."
            moon run $executable:build
          done

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        env:
          ACTOR: ${{ github.actor }}
          REGISTRY: ${{ env.REGISTRY }}
        run: |
          for executable in ${{ steps.executables.outputs.executables }}
          do
            npx zx apps/deployment/src/build-and-push.mjs "$executable"
          done
