name: 'Build and push containers to the Github registry'

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  CYPRESS_INSTALL_BINARY: '0'

jobs:
  build-and-push:
    name: 'Build and push containers to the Github registry'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
        name: Setup Nodejs

      - uses: ./.github/actions/setup-moon
        name: Setup moon

      - uses: ./.github/actions/setup-dasel
        name: Setup dasel

      - name: Get Rust version
        id: rust-version
        run: |
          toolchain_version=$(dasel -r toml --file rust-toolchain.toml '.toolchain.channel')
          echo "toolchain_version=$toolchain_version" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/setup-rust
        name: Setup Rust
        with:
          rust-toolchain: ${{ steps.rust-version.outputs.toolchain_version }}

      - uses: ./.github/actions/setup-python
        name: Setup python environment

      - name: Setup moon dependencies
        run: moon setup

      - name: Generate project dockerfile(s)
        run: npx zx apps/deployment/src/generate-dockerfiles.mjs

      - name: Build the Rust projects
        run: npx zx apps/deployment/src/build-project-type.mjs rust

      - name: Build the Nodejs projects
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} # for admin-website
        run: npx zx apps/deployment/src/build-project-type.mjs nodejs

      - name: Build the misc projects
        run: npx zx apps/deployment/src/build-project-type.mjs miscellaneous

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        env:
          ACTOR: ${{ github.actor }}
          REGISTRY: ${{ env.REGISTRY }}
        run: npx zx apps/deployment/src/build-images-and-push.mjs
