name: 'Build and push containers to the Github registry'

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: 'Build and push containers to the Github registry'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node
        name: Setup Nodejs

      - uses: ./.github/actions/setup-moon
        name: Setup moon

      - uses: ./.github/actions/setup-dasel
        name: Setup dasel

      - name: Get Rust version
        id: rust-version
        run: |
          toolchain_version=$(dasel -r toml --file rust-toolchain.toml '.toolchain.channel')
          echo "toolchain_version=$toolchain_version" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/setup-rust
        name: Setup Rust
        with:
          rust-toolchain: ${{ steps.rust-version.outputs.toolchain_version }}

      - uses: ./.github/actions/setup-python
        name: Setup python environment

      - name: Setup moon dependencies
        run: moon setup

      - name: Get projects executables
        id: executables
        run: |
          all_executables=$(cat apps/deployment/src/data/*.json | jq -r '.apps[].EXECUTABLE_NAMES | flatten[]' | tr '\n' ' ' | xargs)
          echo "all_executables=$all_executables" >> $GITHUB_OUTPUT
          echo "Discovered executables: $all_executables"

      - name: Generate project dockerfile(s)
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          for project in "authenticator" "languages" "executor" "orchestrator" "website" "admin-backend" "admin-website"
          do
            echo "Generating dockerfile for '$project'..."
            poetry run python apps/deployment/src/docker.py "$project"
          done

      - name: Build the Rust projects
        run: |
          for executable in "languages" "executor" "orchestrator" "admin-backend"
          do
            echo "Building executable '$executable'..."
            cargo build --release --package "$executable"
          done

      - name: Build the Nodejs projects
        run: |
          for executable in "website" "admin-website"
          do
            echo "Building executable '$executable'..."
            moon run $executable:build
          done

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        env:
          ACTOR: ${{ github.actor }}
          REGISTRY: ${{ env.REGISTRY }}
        run: |
          all_executables=${{ steps.executables.outputs.all_executables }}
          all_executables=($all_executables)
          for executable in "${all_executables[@]}"
          do
            npx zx apps/deployment/src/build-and-push.mjs "$executable"
          done
